services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${TAG:?error}
    container_name: homepage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - ${BASE_DIR:?error}/config:/app/config # Make sure your local config directory exists
      - ${BASE_DIR:?error}/icons:/app/public/icons
    networks:
      - proxy
      - docker-socket-proxy
    environment:
      PUID: ${UID:?error}
      PGID: ${GID:?error}
      HOMEPAGE_ALLOWED_HOSTS: ${ALLOWED_HOSTS:?error}
    labels:
      # traefik config
      traefik.enable: "true"
      traefik.port: 3000
      traefik.http.routers.homepage.entrypoints: http, https
      traefik.http.routers.homepage.rule: Host(`homepage.${DOMAIN:?error}`)
      traefik.http.routers.homepage.middlewares: ${HTTP_MIDDLEWARES}

      # enable watchtower
      wud.enable: true

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
  docker-socket-proxy
    external: true
