services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - ${CONFIG_DIR:?error}:/app/config # Make sure your local config directory exists
      - ${ICONS_DIR:?error}:/app/public/icons
    networks: 
      - proxy
    environment:
      PUID: ${UID:?error}
      PGID: ${GID:?error}
    labels:
      # traefik config
      traefik.enable: 'true'
      traefik.http.routers.homepage-secure.rule: Host(`homepage.${DOMAIN:?error}`)
      traefik.http.routers.homepage-secure.middlewares: forwardAuth-authentik@file,onlyInternal@file 
      traefik.http.services.homepage.loadbalancer.server.port: 3000
    restart: unless-stopped
    security_opt: 
      - no-new-privileges:true

networks: 
  proxy: 
    external: true
